#include "ShaderManager.hpp"
#include <iostream>
#include "Log.hpp"

// These headers will be generated by CMake using xxd
#include "crt_fs.h"
#include "bayer2x2_fs.h"
#include "bayer4x4_fs.h"

namespace ShaderManager {

Manager::Manager() {}

Manager::~Manager() {
    unloadAll();
}

void Manager::init() {
    if (initialized) return;
    Log::App::Info() << "Initializing Shader Manager";

  loadFromMemory(ShaderType::CRT, resources_shaders_crt_fs);
  loadFromMemory(ShaderType::Bayer2x2, resources_shaders_bayer2x2_fs);
  loadFromMemory(ShaderType::Bayer4x4, resources_shaders_bayer4x4_fs);

  initialized = true;
}

void Manager::loadFromMemory(ShaderType type, const unsigned char* data) {
  if (type == ShaderType::None) return;

  ShaderInstance instance;
  instance.shader = LoadShaderFromMemory(0, (const char*)data);
  instance.renderSizeLoc = GetShaderLocation(instance.shader, "renderSize");
  instance.loaded = true;

  shaders[type] = instance;
}

void Manager::unloadAll() {
  for (auto& [type, instance] : shaders) {
    if (instance.loaded) {
      UnloadShader(instance.shader);
      instance.loaded = false;
    }
  }
  shaders.clear();
}

void Manager::updateUniforms(float width, float height) {
  float renderSize[2] = {width, height};
  for (auto& [type, instance] : shaders) {
    if (instance.loaded) {
      SetShaderValue(instance.shader, instance.renderSizeLoc, renderSize, SHADER_UNIFORM_VEC2);
    }
  }
}

void Manager::begin(ShaderType type) {
  if (type == ShaderType::None) return;

  auto it = shaders.find(type);
  if (it != shaders.end() && it->second.loaded) {
    BeginShaderMode(it->second.shader);
  }
}

void Manager::end() { EndShaderMode(); }

Shader Manager::getShader(ShaderType type) {
  if (type == ShaderType::None) return (Shader){0};

  auto it = shaders.find(type);
  if (it != shaders.end() && it->second.loaded) {
    return it->second.shader;
  }
  return (Shader){0};
}

}  // namespace ShaderManager
